Cast error code to str to allow later startsWith()
Currently when deploying against a localstack instance an error causes the following stacktrace

```
  TypeError: message.startsWith is not a function
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:1150:23
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

We now cast the error code to a string to allow later calls with `startsWith`